[server]
host = "localhost"
port = 8088

[proxy]
timeout = 3000
disable = false

[cache]
dataRoot = "data"

[mappings.wiki]
host = "http://en.wikipedia.org"

[mappings.md5]
host = "http://md5.jsontest.com"
